# permissions for end users to view weatherservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weatherservice-viewer-role
rules:
- apiGroups:
  - weatherservice.iqbal.com
  resources:
  - weatherservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - weatherservice.iqbal.com
  resources:
  - weatherservices/status
  verbs:
  - get
